= My changes

This document was written to describe the changes I have made to this repository to improve the code quality.
Due to the number of changes, I have grouped them by category.

== Code changes

=== Code Style

Each of these changes was made to make the code style consistent between, and within, files.
This makes the code easier to read, and thus maintain.

* Removed `HelloWorld.vue`
+
This file was not used and was unrelated to the application so was just contributing to code clutter.

* Made curly braces consistent between all methods and loops

* Ensured all lines end with a semicolon

* Changed indents to consistently be tabs

* Added type definition to `numbers` array
+
Unnecessary typing errors can mask genuine issues later on.

* Renamed methods to be more descriptive
+
Descriptive method names allow for more easily understandable code

* Commented code and added jsdoc definitions to methods
+
Well commented code is more readable and easy to understand

* Removed unnecessary logging statement
+
The statement was unnecessary to the code execution and was just contributing to code clutter.

=== Performance

* Changed the way the `numbers` array is created
+
The array creation is now done with one operation, which is a vast improvement over the previous method of creating 100 arrays with a spread operator and only keeping the last.
This makes the code more readable and less resource intensive.

* Replaced `document.querySelectorAll` calls with vue's `ref` and reactive styling.
+
Using Vue's built-in reactive state management makes the code easier to read and more performant.
Additionally, the previous method was performing many unnecessary operations (converting strings to numbers, removing classes that didn't exist on most elements) so this also reduces te number of operations that need to be performed.

* Changed to using `ref` and `watch` for rendering the numbers list
+
Using an explicit `watch` definition to trigger an update on the list makes the code clearer and easier to understand.

=== Styling

* Changed text colour to be more visible against the squares
* Increased contrast between the text and the background makes the values easier to read.

* Scoped `style` tag
* Styles should be limited to the defining component to reduce the possibility of conflicting with other stylings.

=== General

|Changed a `var` declaration to `let`
|The loop variable does not need to be declared as global scoped

* The number elements are now generated from a list created with an explicit method call
+
This is an improvement over the previous method which relied on calling the generating method in the `v-for` condition, which could lead to unexpected regeneration later on.

* Made page title relevant to the page
+
This makes the page more user friendly as they can see what the page is while they are in another tab.
